# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Security and Privacy Reading Group
email: martin.kraemer@cs.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  University of Oxford Security and Privacy Reading Group: Information Page and Paper Archive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://markraemer.github.io/ou-secprv/" # the base hostname & protocol for your site
twitter_username: markraemer
github_username:  markraemer

# Build settings
markdown: kramdown
