# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Security Reading Group
email: martin.dehnel-wild@cs.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  University of Oxford Security Reading Group: Information Page and Paper Archive.
baseurl: "/ReadingGroup" # the subpath of your site, e.g. /blog
url: "https://netroware.com" # the base hostname & protocol for your site
twitter_username: mpdehnel
github_username:  mpdehnel

# Build settings
markdown: kramdown

